-- 1. Find all passengers older than the average age:
SELECT passengerName, age 
FROM Passenger 
WHERE age > (
    SELECT AVG(age) 
    FROM Passenger
);

-- 2. List the names of routes that use a Station located in 'City Center':
SELECT routeName, distance 
FROM Route 
WHERE startStationID IN (
    SELECT stationID 
    FROM Station 
    WHERE location = 'City Center'
);

-- 3. Find the tickets purchased by 'Ali Ahmed':

SELECT ticketNumber, price, type 
FROM Ticket 
WHERE passengerID = (
    SELECT passengerID 
    FROM Passenger 
    WHERE passengerName = 'Ali Ahmed'
);

-- 4. Show schedules for routes that are longer than 200 km:
SELECT scheduleID, arrivalTime, departureTime 
FROM Schedule 
WHERE routeID IN (
    SELECT routeID 
    FROM Route 
    WHERE distance > 200
);

-- 5. Find drivers who are assigned to drive a 'Volvo 9400':

SELECT driverName, experience 
FROM Driver 
WHERE driverID IN (
    SELECT driverID 
    FROM Schedule 
    WHERE vehicleID = (
        SELECT vehicleID 
        FROM Vehicle 
        WHERE model = 'Volvo 9400'
    )
);

-- 6. Identify vehicles that operate as Buses:
SELECT vehicleID, capacity, model 
FROM Vehicle 
WHERE vehicleID IN (
    SELECT vehicleID 
    FROM Bus
);

-- 7. Find the most expensive ticket(s) sold:
SELECT ticketNumber, price, type 
FROM Ticket 
WHERE price = (
    SELECT MAX(price) 
    FROM Ticket
);


--Joins 





-- 1. Get full details of a Route (Start and End Station Names):
SELECT r.routeName, s1.stationName AS StartStation, s2.stationName AS EndStation, r.distance
FROM Route r
JOIN Station s1 
    ON r.startStationID = s1.stationID
JOIN Station s2 
    ON r.endStationID = s2.stationID;

-- 2. List all Tickets with their respective Passenger names:
SELECT t.ticketNumber, p.passengerName, t.price, t.type
FROM Ticket t
JOIN Passenger p 
    ON t.passengerID = p.passengerID;

-- 3. Show Schedule details along with the Driver's name:
SELECT s.scheduleID, d.driverName, s.frequency
FROM Schedule s
JOIN Driver d 
    ON s.driverID = d.driverID;

-- 4. Display all Vehicles and their Bus details:
SELECT v.model, v.capacity, b.busNumber, b.busType
FROM Vehicle v
LEFT JOIN Bus b 
    ON v.vehicleID = b.vehicleID;

-- 5. Find which Passenger is traveling on which Route:
SELECT p.passengerName, r.routeName
FROM Ticket t
JOIN Passenger p 
    ON t.passengerID = p.passengerID
JOIN Schedule s 
    ON t.scheduleID = s.scheduleID
JOIN Route r 
    ON s.routeID = r.routeID;

-- 6. Get Total Revenue generated by each Route:
SELECT r.routeName, SUM(t.price) AS TotalRevenue
FROM Ticket t
JOIN Schedule s 
    ON t.scheduleID = s.scheduleID
JOIN Route r 
    ON s.routeID = r.routeID
GROUP BY r.routeName;

-- 7. List all Drivers and the Vehicles they are scheduled to drive:
SELECT d.driverName, v.model, s.frequency
FROM Schedule s
JOIN Driver d 
    ON s.driverID = d.driverID
JOIN Vehicle v 
    ON s.vehicleID = v.vehicleID;






-- Views



-- 1. View of Active Routes:
CREATE OR REPLACE VIEW ActiveRoutes_VW AS
SELECT r.routeID, r.routeName, r.distance, s.stationName AS StartPoint
FROM Route r
JOIN Station s 
    ON r.startStationID = s.stationID;

-- 2. View of Passenger Ticket History:
CREATE OR REPLACE VIEW TicketHistory_VW AS
SELECT p.passengerName, t.ticketNumber, t.price, t.issueDate
FROM Passenger p
JOIN Ticket t 
    ON p.passengerID = t.passengerID;

-- 3. View of Highly Experienced Drivers:
CREATE OR REPLACE VIEW SeniorDrivers_VW AS
SELECT driverName, licenseNumber, experience
FROM Driver
WHERE experience > 10;

-- 4. View of the Train Fleet:
CREATE OR REPLACE VIEW TrainFleet_VW AS
SELECT v.vehicleID, v.model, v.capacity, t.trainNumber, t.numberOfCoaches
FROM Vehicle v
JOIN Train t 
    ON v.vehicleID = t.vehicleID;

-- 5. View of Daily Schedules:
CREATE OR REPLACE VIEW DailySchedules_VW AS
SELECT scheduleID, arrivalTime, departureTime, routeID
FROM Schedule
WHERE frequency = 'Daily';

-- 6. View of Station Analytics:
CREATE OR REPLACE VIEW StationAnalytics_VW AS
SELECT s.stationName, COUNT(r.routeID) AS TotalRoutesStartingHere
FROM Station s
LEFT JOIN Route r 
    ON s.stationID = r.startStationID
GROUP BY s.stationName;

-- 7. View of VIP Passengers:
CREATE OR REPLACE VIEW VIP_Passengers_VW AS
SELECT DISTINCT p.passengerName, p.phoneNumber, t.type
FROM Passenger p
JOIN Ticket t 
    ON p.passengerID = t.passengerID
WHERE t.type = 'VIP';




-- Queries for Views 



-- 1. Fetch data from Active Routes View (e.g., finding routes longer than 100 km):
SELECT routeID, routeName, distance, StartPoint
FROM ActiveRoutes_VW
WHERE distance > 100;

-- 2. Fetch data from Passenger Ticket History View (ordered by most recent issues):
SELECT passengerName, ticketNumber, price, issueDate
FROM TicketHistory_VW
ORDER BY issueDate DESC;

-- 3. Fetch data from Senior Drivers View (e.g., finding those with 12 or more years of experience):
SELECT driverName, licenseNumber, experience
FROM SeniorDrivers_VW
WHERE experience >= 12;

-- 4. Fetch data from Train Fleet View (e.g., finding trains with more than 5 coaches):
SELECT vehicleID, model, trainNumber, numberOfCoaches
FROM TrainFleet_VW
WHERE numberOfCoaches > 5;

-- 5. Fetch data from Daily Schedules View:
SELECT scheduleID, arrivalTime, departureTime, routeID
FROM DailySchedules_VW;

-- 6. Fetch data from Station Analytics View (ordered by stations with the most routes):
SELECT stationName, TotalRoutesStartingHere
FROM StationAnalytics_VW
ORDER BY TotalRoutesStartingHere DESC;

-- 7. Fetch data from VIP Passengers View:
SELECT passengerName, phoneNumber, type
FROM VIP_Passengers_VW;







-- procedures 







-- 1. Procedure with IN Parameter to Add a New Passenger:
CREATE OR REPLACE PROCEDURE Add_Passenger (
    p_id IN NUMBER, 
    p_name IN VARCHAR2, 
    p_email IN VARCHAR2, 
    p_phone IN VARCHAR2,
    p_dob IN DATE,
    p_age IN NUMBER
) IS
BEGIN
    INSERT INTO Passenger (
        passengerID, passengerName, passengerEmail, phoneNumber, DOB, age
    ) VALUES (
        p_id, p_name, p_email, p_phone, p_dob, p_age
    );
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('New passenger added successfully.');
END Add_Passenger;
/








-- 2. Procedure with an OUT Parameter to count tickets for a specific schedule:
CREATE OR REPLACE PROCEDURE Count_Schedule_Tickets (
    p_scheduleID IN NUMBER, 
    v_total_tickets OUT NUMBER
) IS
BEGIN
    SELECT COUNT(*) 
    INTO v_total_tickets 
    FROM Ticket 
    WHERE scheduleID = p_scheduleID;
END Count_Schedule_Tickets;
/






-- 3. Procedure with an IN OUT Parameter to calculate and return a discounted price:
CREATE OR REPLACE PROCEDURE Apply_Special_Discount (
    p_ticketID IN NUMBER, 
    p_price_mod IN OUT NUMBER
) IS
BEGIN
    -- Subtracting the IN OUT value from current price
    UPDATE Ticket
    SET price = price - p_price_mod
    WHERE ticketNumber = p_ticketID;
    
    -- Fetching the updated price to send back via the same IN OUT parameter
    SELECT price 
    INTO p_price_mod 
    FROM Ticket 
    WHERE ticketNumber = p_ticketID;
    
    COMMIT;
END Apply_Special_Discount;
/

-- 4. Procedure using a FOR Loop to print all drivers with high experience:
CREATE OR REPLACE PROCEDURE Print_Senior_Drivers (
    p_min_experience IN NUMBER
) IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Senior Drivers List:');
    FOR i IN (
        SELECT driverName, experience 
        FROM Driver 
        WHERE experience >= p_min_experience
    ) 
    LOOP
        DBMS_OUTPUT.PUT_LINE(i.driverName || ' - ' || i.experience || ' years');
    END LOOP;
END Print_Senior_Drivers;
/

-- 5. Procedure using SELECT INTO to get and print a Passenger's Email:
CREATE OR REPLACE PROCEDURE Print_Passenger_Email (
    p_passID IN NUMBER
) IS
    v_email VARCHAR2(100);
BEGIN
    SELECT passengerEmail 
    INTO v_email 
    FROM Passenger 
    WHERE passengerID = p_passID;
    
    DBMS_OUTPUT.PUT_LINE('Passenger Email: ' || v_email);
END Print_Passenger_Email;
/

-- 6. Procedure to safely cancel a ticket and free up schedule space:
CREATE OR REPLACE PROCEDURE Cancel_Passenger_Ticket (
    p_ticket_num IN NUMBER
) IS
BEGIN
    DELETE FROM Ticket 
    WHERE ticketNumber = p_ticket_num;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Ticket ' || p_ticket_num || ' has been cancelled.');
END Cancel_Passenger_Ticket;
/

-- 7. Procedure using a FOR Loop to show all routes starting from a specific station:
CREATE OR REPLACE PROCEDURE Print_Station_Routes (
    p_stationID IN NUMBER
) IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Routes starting from Station ID: ' || p_stationID);
    FOR i IN (
        SELECT routeName, distance 
        FROM Route 
        WHERE startStationID = p_stationID
    ) 
    LOOP
        DBMS_OUTPUT.PUT_LINE('Route: ' || i.routeName || ' | Distance: ' || i.distance || 'km');
    END LOOP;
END Print_Station_Routes;




-- Queries for Procedures 

--1  


DECLARE

    v_id NUMBER := 17;

    v_name VARCHAR2(100) := 'Taheer Bin Yousaf';

    v_email VARCHAR2(100) := 'taheer@email.com';

    v_phone VARCHAR2(20) := '03211234567';

    v_dob DATE := TO_DATE('2002-08-15', 'YYYY-MM-DD');

    v_age NUMBER := 21;

BEGIN

    -- Call the procedure

    Add_Passenger(v_id, v_name, v_email, v_phone, v_dob, v_age);

    

    -- Print the full output of what was inserted

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

    DBMS_OUTPUT.PUT_LINE('      PASSENGER INSERTED            ');

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

    DBMS_OUTPUT.PUT_LINE('Passenger ID   : ' || v_id);

    DBMS_OUTPUT.PUT_LINE('Passenger Name : ' || v_name);

    DBMS_OUTPUT.PUT_LINE('Email Address  : ' || v_email);

    DBMS_OUTPUT.PUT_LINE('Phone Number   : ' || v_phone);

    DBMS_OUTPUT.PUT_LINE('Date of Birth  : ' || TO_CHAR(v_dob, 'DD-MON-YYYY'));

    DBMS_OUTPUT.PUT_LINE('Calculated Age : ' || v_age);

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

END;

/





2

DECLARE

    v_sched_id NUMBER := 1;

    v_total NUMBER;

BEGIN

    -- Call procedure to fill the OUT parameter (v_total)

    Count_Schedule_Tickets(p_scheduleID => v_sched_id, v_total_tickets => v_total);

    

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

    DBMS_OUTPUT.PUT_LINE('      SCHEDULE TICKET COUNT         ');

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

    DBMS_OUTPUT.PUT_LINE('Schedule ID Checked : ' || v_sched_id);

    DBMS_OUTPUT.PUT_LINE('Total Tickets Sold  : ' || v_total);

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

END;

/



3

DECLARE

    v_ticket_id NUMBER := 2; 

    v_discount NUMBER := 200; 

BEGIN

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

    DBMS_OUTPUT.PUT_LINE('      APPLYING TICKET DISCOUNT      ');

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

    DBMS_OUTPUT.PUT_LINE('Ticket Number       : ' || v_ticket_id);

    DBMS_OUTPUT.PUT_LINE('Discount Amount     : Rs. ' || v_discount);

    

    -- Call procedure (v_discount will be overwritten with the new total price)

    Apply_Special_Discount(p_ticketID => v_ticket_id, p_price_mod => v_discount);

    

    DBMS_OUTPUT.PUT_LINE('New Updated Price   : Rs. ' || v_discount);

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

END;

/











4

BEGIN

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

    DBMS_OUTPUT.PUT_LINE('   FETCHING SENIOR DRIVERS (10+ Yrs)');

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

    

    Print_Senior_Drivers(p_min_experience => 10);

    

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

END;

/















5



BEGIN

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

    DBMS_OUTPUT.PUT_LINE('   FETCHING PASSENGER CONTACT INFO  ');

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

    DBMS_OUTPUT.PUT_LINE('Checking for Passenger ID: 1');

    

    Print_Passenger_Email(p_passID => 1);

    

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

END;

/





6



DECLARE

    v_ticket_to_cancel NUMBER := 20;

BEGIN

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

    DBMS_OUTPUT.PUT_LINE('      TICKET CANCELLATION PROCESS   ');

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

    DBMS_OUTPUT.PUT_LINE('Target Ticket Number : ' || v_ticket_to_cancel);

    

    Cancel_Passenger_Ticket(p_ticket_num => v_ticket_to_cancel);

    

    DBMS_OUTPUT.PUT_LINE('Status               : Deletion executed.');

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

END;

/





7



DECLARE

    v_origin_station NUMBER := 1;

BEGIN

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

    DBMS_OUTPUT.PUT_LINE('        STATION ROUTE INQUIRY       ');

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

    DBMS_OUTPUT.PUT_LINE('Origin Station ID : ' || v_origin_station);

    

    Print_Station_Routes(p_stationID => v_origin_station);

    

    DBMS_OUTPUT.PUT_LINE('------------------------------------');

END;

/




-- Trigger 




-- 1. Trigger to automatically enforce a minimum ticket price of 50:
CREATE OR REPLACE TRIGGER trg_enforce_min_price
BEFORE INSERT OR UPDATE ON Ticket
FOR EACH ROW
BEGIN
    IF :NEW.price < 50 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Error: Minimum ticket price must be at least Rs. 50.');
    END IF;
END;
/

-- 2. Trigger to dynamically calculate Passenger Age based on DOB on insert:
CREATE OR REPLACE TRIGGER trg_auto_calc_age
BEFORE INSERT OR UPDATE ON Passenger
FOR EACH ROW
BEGIN
    IF :NEW.DOB IS NOT NULL THEN
        :NEW.age := TRUNC(MONTHS_BETWEEN(SYSDATE, :NEW.DOB) / 12);
    END IF;
END;
/

-- 3. Trigger to prevent a Schedule from having the same Start and End time:
CREATE OR REPLACE TRIGGER trg_prevent_zero_duration
BEFORE INSERT OR UPDATE ON Schedule
FOR EACH ROW
BEGIN
    IF :NEW.arrivalTime = :NEW.departureTime THEN
        RAISE_APPLICATION_ERROR(-20002, 'Error: Arrival and Departure times cannot be identical.');
    END IF;
END;
/

-- 4. Trigger to ensure Bus Names are always stored in UPPERCASE:
CREATE OR REPLACE TRIGGER trg_uppercase_bus_number
BEFORE INSERT OR UPDATE ON Bus
FOR EACH ROW
BEGIN
    :NEW.busNumber := UPPER(:NEW.busNumber);
END;
/

-- 5. Trigger to default the Ticket Type to 'Standard' if user forgets to enter one:
CREATE OR REPLACE TRIGGER trg_default_ticket_type
BEFORE INSERT ON Ticket
FOR EACH ROW
BEGIN
    IF :NEW.type IS NULL THEN
        :NEW.type := 'Standard';
    END IF;
END;
/

-- 6. Trigger to prevent a Route distance from being updated to a smaller value:
CREATE OR REPLACE TRIGGER trg_prevent_distance_shrink
BEFORE UPDATE ON Route
FOR EACH ROW
BEGIN
    IF :NEW.distance < :OLD.distance THEN
        RAISE_APPLICATION_ERROR(-20003, 'Error: Route distance cannot be decreased once established.');
    END IF;
END;
/

-- 7. Trigger to ensure new Drivers have at least 1 year of experience:
CREATE OR REPLACE TRIGGER trg_minimum_driver_experience
BEFORE INSERT ON Driver
FOR EACH ROW
BEGIN
    IF :NEW.experience < 1 THEN
        RAISE_APPLICATION_ERROR(-20004, 'Error: Driver must have at least 1 year of experience.');
    END IF;
END;





-- Queries triggering the triggers 









1-- Intentionally trying to insert a ticket with a price of 20

INSERT INTO Ticket (ticketNumber, price, type, issueDate, passengerID, scheduleID) 

VALUES (999, 20, 'Economy', SYSDATE, 1, 1);







2-- Insert a passenger without providing their age, only their DOB

INSERT INTO Passenger (passengerID, passengerName, DOB) 

VALUES (100, 'Test Passenger', TO_DATE('2000-01-01', 'YYYY-MM-DD'));



2-- Show the professor that the age was automatically calculated and filled in!

SELECT passengerName, DOB, age FROM Passenger WHERE passengerID = 100;





3-- Try to update a schedule to have the exact same arrival and departure time

UPDATE Schedule 

SET arrivalTime = TO_TIMESTAMP('2024-01-15 10:00:00', 'YYYY-MM-DD HH24:MI:SS'),

    departureTime = TO_TIMESTAMP('2024-01-15 10:00:00', 'YYYY-MM-DD HH24:MI:SS')

WHERE scheduleID = 1;









4-- Insert a bus using messy lowercase letters

INSERT INTO Bus (vehicleID, busNumber, busType) 

VALUES (2, 'lhe-fsd-xyz', 'Standard');



4-- Select it to show the professor the trigger fixed it to 'LHE-FSD-XYZ'

SELECT vehicleID, busNumber FROM Bus WHERE vehicleID = 2;









5-- Insert a ticket but leave the 'type' column completely empty (NULL)

INSERT INTO Ticket (ticketNumber, price, issueDate, passengerID, scheduleID) 

VALUES (998, 500, SYSDATE, 1, 1);



5-- Select it to show that 'Standard' was automatically inserted

SELECT ticketNumber, price, type FROM Ticket WHERE ticketNumber = 998;









6-- Try to update Route 1 (which is 120km) down to just 10km

UPDATE Route 

SET distance = 10 

WHERE routeID = 1;







7-- Intentionally try to insert a rookie driver with 0 experience

INSERT INTO Driver (driverID, driverName, licenseNumber, experience) 

VALUES (100, 'New Guy', 'LIC-999', 0);
